steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/preflight-hackathon/full-shelf-repo/orchestrator:v1', '-f', 'apps/orchestrator/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/preflight-hackathon/full-shelf-repo/orchestrator:v1'
