// =====================================================================
// Full Shelf — deterministic simulated-telematics fixture
// ---------------------------------------------------------------------
// SIMULATED_TELEMETRY. Every sample below is generated by interpolating
// between DEMO_TENANT_LOCATION_REFERENCE facility coordinates on a fixed
// two-minute cadence. No coordinate is invented, geocoded or observed.
//
// Truck 1 (TRUCK-01): HUB → Agency 01 (delivered) → toward Agency 02.
//   Its samples STOP at 08:20 because the vehicle stopped reporting
//   movement after the reported refrigeration fault. The stopping of
//   samples is a consequence of the fault, never the evidence for it.
//
// Truck 2 (TRUCK-02): HUB → Agency 04 → toward Agency 05, unaffected.
//
// The single health event is authored separately and is the ONLY thing
// that may place a vehicle in a failed contextual status.
// =====================================================================

import { locationFor } from "../contract/locations";
import {
  TELEMETRY_CLASSIFICATION,
  type TelemetryFeed,
  type VehicleHealthEvent,
  type VehicleLocationSample,
  type VehicleTelemetryDataSource,
} from "./types";

export const TELEMETRY_FIXTURE_ID = "sim-telematics-2026-08-14-v1";

/** Operating day and cadence are fixed so playback is reproducible. */
const DAY = "2026-08-14";
const CADENCE_MINUTES = 2;

/** 08:00 → "2026-08-14T08:00:00+00:00" */
function instant(minutesFromMidnight: number): string {
  const h = Math.floor(minutesFromMidnight / 60);
  const m = minutesFromMidnight % 60;
  return `${DAY}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:00+00:00`;
}

export function minutesOf(iso: string): number {
  const m = /T(\d{2}):(\d{2})/.exec(iso);
  if (!m) throw new Error(`Unparseable telemetry instant \`${iso}\``);
  return Number(m[1]) * 60 + Number(m[2]);
}

/** A leg of a vehicle's planned run, expressed only in facility keys. */
interface Leg {
  from: string;
  to: string;
  /** Minutes-from-midnight when the vehicle leaves `from`. */
  departs: number;
  /** Minutes-from-midnight when it arrives at `to`. */
  arrives: number;
}

function samplesForLegs(vehicleId: string, legs: Leg[]): VehicleLocationSample[] {
  const out: VehicleLocationSample[] = [];
  for (const leg of legs) {
    const a = locationFor(leg.from);
    const b = locationFor(leg.to);
    // No configured location → emit nothing. Never fabricate a position.
    if (!a || !b) continue;

    for (let t = leg.departs; t <= leg.arrives; t += CADENCE_MINUTES) {
      const span = leg.arrives - leg.departs;
      const f = span === 0 ? 1 : (t - leg.departs) / span;
      const recordedAt = instant(t);
      // A vehicle sitting at a facility repeats the same coordinate on
      // consecutive samples. That is normal and must stay harmless.
      if (out.length && out[out.length - 1].recorded_at === recordedAt) continue;
      out.push({
        sample_id: `${vehicleId}-${String(t).padStart(4, "0")}`,
        vehicle_id: vehicleId,
        recorded_at: recordedAt,
        latitude: round6(a.lat + (b.lat - a.lat) * f),
        longitude: round6(a.lng + (b.lng - a.lng) * f),
        source_classification: TELEMETRY_CLASSIFICATION,
      });
    }
  }
  return out;
}

const round6 = (n: number) => Math.round(n * 1e6) / 1e6;

// Truck 1 completes O201 at Agency 01, then heads toward Agency 02 and
// stops reporting at 08:20 — the instant the fault is reported.
const TRUCK_1_SAMPLES = samplesForLegs("TRUCK-01", [
  { from: "HUB", to: "Agency 01", departs: 7 * 60 + 30, arrives: 8 * 60 + 4 },
  { from: "Agency 01", to: "Agency 01", departs: 8 * 60 + 6, arrives: 8 * 60 + 10 }, // dwelling: repeated coordinate
  { from: "Agency 01", to: "Agency 02", departs: 8 * 60 + 12, arrives: 8 * 60 + 40 },
]).filter((s) => minutesOf(s.recorded_at) <= 8 * 60 + 20);

// Truck 2 is unaffected and keeps reporting through the whole window.
const TRUCK_2_SAMPLES = samplesForLegs("TRUCK-02", [
  { from: "HUB", to: "Agency 04", departs: 7 * 60 + 40, arrives: 8 * 60 + 18 },
  { from: "Agency 04", to: "Agency 04", departs: 8 * 60 + 20, arrives: 8 * 60 + 24 },
  { from: "Agency 04", to: "Agency 05", departs: 8 * 60 + 26, arrives: 9 * 60 + 0 },
]);

/**
 * The explicit fault. Reported by the vehicle's refrigeration
 * controller — an input Full Shelf receives, not a conclusion it draws.
 * Carries no revision, no orders and no recovery.
 */
const HEALTH_EVENTS: VehicleHealthEvent[] = [
  {
    event_id: "VHE-2026-08-14-0001",
    vehicle_id: "TRUCK-01",
    event_type: "REFRIGERATION_FAILURE_REPORTED",
    reported_at: instant(8 * 60 + 20),
    source_type: "REEFER_CONTROLLER",
    source_classification: TELEMETRY_CLASSIFICATION,
  },
];

const ALL_SAMPLES = [...TRUCK_1_SAMPLES, ...TRUCK_2_SAMPLES].sort((a, b) =>
  a.recorded_at === b.recorded_at
    ? a.vehicle_id.localeCompare(b.vehicle_id)
    : a.recorded_at.localeCompare(b.recorded_at),
);

/**
 * Deterministic replay of the checked-in fixture. Nothing after `asOf`
 * is ever returned, so a boundary cannot leak future position or future
 * faults into an earlier view.
 */
export class FixtureTelemetryDataSource implements VehicleTelemetryDataSource {
  readonly classification = TELEMETRY_CLASSIFICATION;

  feedAsOf(asOf: string): TelemetryFeed {
    const cutoff = minutesOf(asOf);
    return {
      fixture_id: TELEMETRY_FIXTURE_ID,
      samples: ALL_SAMPLES.filter((s) => minutesOf(s.recorded_at) <= cutoff),
      health_events: HEALTH_EVENTS.filter((e) => minutesOf(e.reported_at) <= cutoff),
    };
  }
}

/** Exported for tests that assert on the full authored fixture. */
export const FULL_TELEMETRY_FIXTURE: TelemetryFeed = {
  fixture_id: TELEMETRY_FIXTURE_ID,
  samples: ALL_SAMPLES,
  health_events: HEALTH_EVENTS,
};
